### ISSUE TITLE
Runtime error on windows

### ISSUE THREAD

**Issue by Cynede** [nickel-org/session#2]
even on this code

``` rust
    server.get("/", middleware! { |req, mut res|
        format!("You are logged in as: {:?}\n", CookieSession::get_mut(req, &mut res))
    });
```

![capture](https://cloud.githubusercontent.com/assets/2656965/16110447/d0695b90-33be-11e6-9a78-507afe592740.JPG)

**Comment by Ryman** [comment]
Do you have a backtrace available for this or a translation of the error given? I don't have a windows machine easily accessible to check this on.

**Comment by Cynede** [comment]
@Ryman ordinal number not found in library DLL, will check trace some later

**Comment by Cynede** [comment]
can't reproduce on Linux

**Comment by Ryman** [comment]
That's somewhat positive to hear! Can you share more details of your environment along with the backtrace? Which variant of the Windows compiler are you using (msvc?) and what version?

**Comment by Cynede** [comment]
@Ryman msvc from recent vs 2015, don't know how to trace it

**Comment by Cynede** [comment]
@Ryman resolved, it was due bad `ssleay` dll I used there! \o/
